export const tapPhim = [
    {
        air_date: '2023-10-05',
        episode_number: 1,
        episode_type: 'standard',
        id: 4447686,
        name: 'Ouroboros',
        overview: 'Loki finds himself lost to time and torn, quite literally, between past, present and future.',
        production_code: '',
        runtime: 48,
        season_number: 2,
        show_id: 84958,
        still_path: '/d4S2xNIEb0DNUxi3L6p1SDxNiLR.jpg',
        vote_average: 7.8,
        vote_count: 30,
        crew: [
            {
                job: 'First Assistant Director',
                department: 'Directing',
                credit_id: '60c07332960cde0040f22be9',
                adult: false,
                gender: 2,
                id: 1868277,
                known_for_department: 'Directing',
                name: 'Richard Graves',
                original_name: 'Richard Graves',
                popularity: 0.6,
                profile_path: null,
            },
            {
                job: 'Editor',
                department: 'Editing',
                credit_id: '60d2e8b4a27502005fd3a237',
                adult: false,
                gender: 0,
                id: 1333652,
                known_for_department: 'Editing',
                name: 'Calum Ross',
                original_name: 'Calum Ross',
                popularity: 3.586,
                profile_path: null,
            },
            {
                job: 'Writer',
                department: 'Writing',
                credit_id: '60dc207bef9d7200478a67a8',
                adult: false,
                gender: 2,
                id: 3119335,
                known_for_department: 'Writing',
                name: 'Eric Martin',
                original_name: 'Eric Martin',
                popularity: 0.74,
                profile_path: null,
            },
            {
                job: 'Director',
                department: 'Directing',
                credit_id: '64c73df895ce2401012fe287',
                adult: false,
                gender: 2,
                id: 1074560,
                known_for_department: 'Writing',
                name: 'Justin Benson',
                original_name: 'Justin Benson',
                popularity: 2.222,
                profile_path: '/mch4MNcOxVsej3O5ifugkZTFzWI.jpg',
            },
            {
                job: 'Director',
                department: 'Directing',
                credit_id: '64c73dfc63e6fb00e12b8b8d',
                adult: false,
                gender: 2,
                id: 583479,
                known_for_department: 'Directing',
                name: 'Aaron Moorhead',
                original_name: 'Aaron Moorhead',
                popularity: 2.374,
                profile_path: '/plvZ27ya8yxyyqSCHbwBMjFfJwS.jpg',
            },
            {
                job: 'Director of Photography',
                department: 'Camera',
                credit_id: '651f6d46072166011c042d76',
                adult: false,
                gender: 2,
                id: 1116311,
                known_for_department: 'Camera',
                name: 'Isaac Bauman',
                original_name: 'Isaac Bauman',
                popularity: 0.6,
                profile_path: '/cDXi2tFKOrHmexdzXydntTAFKbs.jpg',
            },
            {
                job: 'Second Assistant Director',
                department: 'Directing',
                credit_id: '651f6dc274507d011c1082f3',
                adult: false,
                gender: 0,
                id: 2469813,
                known_for_department: 'Directing',
                name: 'Sallie Hard',
                original_name: 'Sallie Hard',
                popularity: 1.2,
                profile_path: null,
            },
            {
                job: 'Second Unit Director',
                department: 'Directing',
                credit_id: '651f6fb75b124000c60596bb',
                adult: false,
                gender: 0,
                id: 1408337,
                known_for_department: 'Visual Effects',
                name: 'Christopher Townsend',
                original_name: 'Christopher Townsend',
                popularity: 1.102,
                profile_path: null,
            },
        ],
        guest_stars: [
            {
                character: 'Mail Cart Driver',
                credit_id: '651f70c8072166011c04303f',
                order: 570,
                adult: false,
                gender: 1,
                id: 1614139,
                known_for_department: 'Acting',
                name: 'Charlie Cameron',
                original_name: 'Charlie Cameron',
                popularity: 0.6,
                profile_path: '/lTYzy7hAcfsK4PYpyGcSrk6wxVa.jpg',
            },
            {
                character: 'General Dox',
                credit_id: '651f7e070721660139c84990',
                order: 571,
                adult: false,
                gender: 1,
                id: 71083,
                known_for_department: 'Acting',
                name: 'Kate Dickie',
                original_name: 'Kate Dickie',
                popularity: 7.28,
                profile_path: '/mlFYUmZycpRa7TGgDTfP0xanE1Q.jpg',
            },
            {
                character: 'Judge Gamble',
                credit_id: '651f7e0ff04d01011c462db0',
                order: 572,
                adult: false,
                gender: 1,
                id: 1232690,
                known_for_department: 'Acting',
                name: 'Liz Carr',
                original_name: 'Liz Carr',
                popularity: 3.1,
                profile_path: '/6BT2hgkSAPO7ceBT2VDcQT4pVSc.jpg',
            },
            {
                character: 'Hunter D-90',
                credit_id: '651f801a74507d00ac4847b6',
                order: 573,
                adult: false,
                gender: 2,
                id: 1194878,
                known_for_department: 'Acting',
                name: 'Neil Ellice',
                original_name: 'Neil Ellice',
                popularity: 7.638,
                profile_path: '/rDXkFLRNOJiWFqyyynplHjvwWwf.jpg',
            },
            {
                character: "McDonald's Manager (uncredited)",
                credit_id: '6528d7e9629b2c00ffef27e6',
                order: 577,
                adult: false,
                gender: 2,
                id: 1945216,
                known_for_department: 'Acting',
                name: 'Jack Cunningham-Nuttall',
                original_name: 'Jack Cunningham-Nuttall',
                popularity: 1.176,
                profile_path: '/cUusBhc34zHPvE0KNCdHudRYdhE.jpg',
            },
            {
                character: 'Hunter X-5',
                credit_id: '6531de45481382011c20c256',
                order: 583,
                adult: false,
                gender: 2,
                id: 1932179,
                known_for_department: 'Acting',
                name: 'Rafael Casal',
                original_name: 'Rafael Casal',
                popularity: 3.632,
                profile_path: '/9PaSpVV6aU3rtFXG7oOpnEu92gv.jpg',
            },
        ],
    },
    {
        air_date: '2023-10-12',
        episode_number: 2,
        episode_type: 'standard',
        id: 4447779,
        name: 'Breaking Brad',
        overview:
            'With the TVA on the verge of a temporal meltdown, Loki & Mobius will stop at nothing to find Sylvie.',
        production_code: '',
        runtime: 52,
        season_number: 2,
        show_id: 84958,
        still_path: '/wFbZaHRtG7xLgUJINdX2t8LHzTU.jpg',
        vote_average: 7,
        vote_count: 18,
        crew: [
            {
                job: 'Writer',
                department: 'Writing',
                credit_id: '60dc207bef9d7200478a67a8',
                adult: false,
                gender: 2,
                id: 3119335,
                known_for_department: 'Writing',
                name: 'Eric Martin',
                original_name: 'Eric Martin',
                popularity: 0.74,
                profile_path: null,
            },
            {
                job: 'Editor',
                department: 'Editing',
                credit_id: '60dc21bad95420007ea0f756',
                adult: false,
                gender: 0,
                id: 1408363,
                known_for_department: 'Editing',
                name: 'Emma McCleave',
                original_name: 'Emma McCleave',
                popularity: 0.84,
                profile_path: null,
            },
            {
                job: 'Second Assistant Director',
                department: 'Directing',
                credit_id: '651f6dc274507d011c1082f3',
                adult: false,
                gender: 0,
                id: 2469813,
                known_for_department: 'Directing',
                name: 'Sallie Hard',
                original_name: 'Sallie Hard',
                popularity: 1.2,
                profile_path: null,
            },
            {
                job: 'Director',
                department: 'Directing',
                credit_id: '6527821dcedac400e2136c76',
                adult: false,
                gender: 2,
                id: 1590413,
                known_for_department: 'Visual Effects',
                name: 'Dan DeLeeuw',
                original_name: 'Dan DeLeeuw',
                popularity: 0.953,
                profile_path: null,
            },
            {
                job: 'Director of Photography',
                department: 'Camera',
                credit_id: '6528d627fd63005d78d8a3d1',
                adult: false,
                gender: 0,
                id: 1428915,
                known_for_department: 'Camera',
                name: 'Oliver Loncraine',
                original_name: 'Oliver Loncraine',
                popularity: 1.4,
                profile_path: null,
            },
            {
                job: 'First Assistant Director',
                department: 'Directing',
                credit_id: '6528d6530cb33516f8822a66',
                adult: false,
                gender: 0,
                id: 1824241,
                known_for_department: 'Directing',
                name: 'Joe Geary',
                original_name: 'Joe Geary',
                popularity: 0.6,
                profile_path: null,
            },
            {
                job: 'Visual Effects Supervisor',
                department: 'Visual Effects',
                credit_id: '6528d6c3ea84c7010c1ad17d',
                adult: false,
                gender: 0,
                id: 3580730,
                known_for_department: 'Visual Effects',
                name: 'Sandra Balej',
                original_name: 'Sandra Balej',
                popularity: 0.6,
                profile_path: null,
            },
        ],
        guest_stars: [
            {
                character: 'General Dox',
                credit_id: '651f7e070721660139c84990',
                order: 571,
                adult: false,
                gender: 1,
                id: 71083,
                known_for_department: 'Acting',
                name: 'Kate Dickie',
                original_name: 'Kate Dickie',
                popularity: 7.28,
                profile_path: '/mlFYUmZycpRa7TGgDTfP0xanE1Q.jpg',
            },
            {
                character: 'Hunter D-90',
                credit_id: '651f801a74507d00ac4847b6',
                order: 573,
                adult: false,
                gender: 2,
                id: 1194878,
                known_for_department: 'Acting',
                name: 'Neil Ellice',
                original_name: 'Neil Ellice',
                popularity: 7.638,
                profile_path: '/rDXkFLRNOJiWFqyyynplHjvwWwf.jpg',
            },
            {
                character: 'Reporter #1',
                credit_id: '6528d7b1700bf7013a5dd39a',
                order: 574,
                adult: false,
                gender: 0,
                id: 4318339,
                known_for_department: 'Acting',
                name: 'Dhanushka Anson',
                original_name: 'Dhanushka Anson',
                popularity: 0.6,
                profile_path: null,
            },
            {
                character: 'Reporter #2',
                credit_id: '6528d7bb0cb33516fd48cede',
                order: 575,
                adult: false,
                gender: 0,
                id: 4318340,
                known_for_department: 'Acting',
                name: 'Roger Parkins',
                original_name: 'Roger Parkins',
                popularity: 0.6,
                profile_path: null,
            },
            {
                character: "McDonald's Manager",
                credit_id: '6528d7c9fd63005d7990625a',
                order: 576,
                adult: false,
                gender: 2,
                id: 1945216,
                known_for_department: 'Acting',
                name: 'Jack Cunningham-Nuttall',
                original_name: 'Jack Cunningham-Nuttall',
                popularity: 1.176,
                profile_path: '/cUusBhc34zHPvE0KNCdHudRYdhE.jpg',
            },
            {
                character: 'Bill',
                credit_id: '6528d7fe0cb33516f63da0aa',
                order: 578,
                adult: false,
                gender: 0,
                id: 1947519,
                known_for_department: 'Acting',
                name: 'Sion Lloyd',
                original_name: 'Sion Lloyd',
                popularity: 1.094,
                profile_path: null,
            },
            {
                character: 'Punk',
                credit_id: '6528d83481383100c48aa8a4',
                order: 579,
                adult: false,
                gender: 0,
                id: 4318341,
                known_for_department: 'Acting',
                name: 'Sam Brennan',
                original_name: 'Sam Brennan',
                popularity: 0.6,
                profile_path: null,
            },
            {
                character: 'Brad Wolfe',
                credit_id: '6531de3fefe37c00e42d0b8a',
                order: 582,
                adult: false,
                gender: 2,
                id: 1932179,
                known_for_department: 'Acting',
                name: 'Rafael Casal',
                original_name: 'Rafael Casal',
                popularity: 3.632,
                profile_path: '/9PaSpVV6aU3rtFXG7oOpnEu92gv.jpg',
            },
        ],
    },
    {
        air_date: '2023-10-19',
        episode_number: 3,
        episode_type: 'standard',
        id: 4447780,
        name: '1893',
        overview: 'Loki & Mobius go on the hunt to find everyone’s favorite cartoon clock as they try to save the TVA.',
        production_code: '',
        runtime: 56,
        season_number: 2,
        show_id: 84958,
        still_path: '/bz0G1oeaNy0N9iBTUImfiQYFRez.jpg',
        vote_average: 6.1,
        vote_count: 7,
        crew: [
            {
                job: 'First Assistant Director',
                department: 'Directing',
                credit_id: '60c07332960cde0040f22be9',
                adult: false,
                gender: 2,
                id: 1868277,
                known_for_department: 'Directing',
                name: 'Richard Graves',
                original_name: 'Richard Graves',
                popularity: 0.6,
                profile_path: null,
            },
            {
                job: 'Editor',
                department: 'Editing',
                credit_id: '60dc21bad95420007ea0f756',
                adult: false,
                gender: 0,
                id: 1408363,
                known_for_department: 'Editing',
                name: 'Emma McCleave',
                original_name: 'Emma McCleave',
                popularity: 0.84,
                profile_path: null,
            },
            {
                job: 'Director of Photography',
                department: 'Camera',
                credit_id: '651f6d46072166011c042d76',
                adult: false,
                gender: 2,
                id: 1116311,
                known_for_department: 'Camera',
                name: 'Isaac Bauman',
                original_name: 'Isaac Bauman',
                popularity: 0.6,
                profile_path: '/cDXi2tFKOrHmexdzXydntTAFKbs.jpg',
            },
            {
                job: 'Second Assistant Director',
                department: 'Directing',
                credit_id: '651f6dc274507d011c1082f3',
                adult: false,
                gender: 0,
                id: 2469813,
                known_for_department: 'Directing',
                name: 'Sallie Hard',
                original_name: 'Sallie Hard',
                popularity: 1.2,
                profile_path: null,
            },
            {
                job: 'Second Unit Director',
                department: 'Directing',
                credit_id: '651f6fb75b124000c60596bb',
                adult: false,
                gender: 0,
                id: 1408337,
                known_for_department: 'Visual Effects',
                name: 'Christopher Townsend',
                original_name: 'Christopher Townsend',
                popularity: 1.102,
                profile_path: null,
            },
            {
                job: 'Director',
                department: 'Directing',
                credit_id: '65278226629b2c00ac5f82bf',
                adult: false,
                gender: 0,
                id: 1077115,
                known_for_department: 'Art',
                name: 'Kasra Farahani',
                original_name: 'Kasra Farahani',
                popularity: 1.4,
                profile_path: null,
            },
            {
                job: 'Teleplay',
                department: 'Writing',
                credit_id: '65278246cedac400e2136c91',
                adult: false,
                gender: 0,
                id: 1077115,
                known_for_department: 'Art',
                name: 'Kasra Farahani',
                original_name: 'Kasra Farahani',
                popularity: 1.4,
                profile_path: null,
            },
            {
                job: 'Story',
                department: 'Writing',
                credit_id: '65278260fd63005d7a2d3146',
                adult: false,
                gender: 2,
                id: 3119335,
                known_for_department: 'Writing',
                name: 'Eric Martin',
                original_name: 'Eric Martin',
                popularity: 0.74,
                profile_path: null,
            },
            {
                job: 'Teleplay',
                department: 'Writing',
                credit_id: '65278265fd63005d78d809e2',
                adult: false,
                gender: 2,
                id: 3119335,
                known_for_department: 'Writing',
                name: 'Eric Martin',
                original_name: 'Eric Martin',
                popularity: 0.74,
                profile_path: null,
            },
            {
                job: 'First Assistant Director',
                department: 'Directing',
                credit_id: '6528d6530cb33516f8822a66',
                adult: false,
                gender: 0,
                id: 1824241,
                known_for_department: 'Directing',
                name: 'Joe Geary',
                original_name: 'Joe Geary',
                popularity: 0.6,
                profile_path: null,
            },
            {
                job: 'Visual Effects Supervisor',
                department: 'Visual Effects',
                credit_id: '6528d6c3ea84c7010c1ad17d',
                adult: false,
                gender: 0,
                id: 3580730,
                known_for_department: 'Visual Effects',
                name: 'Sandra Balej',
                original_name: 'Sandra Balej',
                popularity: 0.6,
                profile_path: null,
            },
            {
                job: 'Teleplay',
                department: 'Writing',
                credit_id: '6531d508b2681f00feb063f3',
                adult: false,
                gender: 0,
                id: 1800206,
                known_for_department: 'Writing',
                name: "Jason O'Leary",
                original_name: "Jason O'Leary",
                popularity: 0.6,
                profile_path: null,
            },
        ],
        guest_stars: [
            {
                character: 'Robber Baron',
                credit_id: '6531de17b2681f00e13a7138',
                order: 580,
                adult: false,
                gender: 2,
                id: 1222025,
                known_for_department: 'Acting',
                name: 'Richard Dixon',
                original_name: 'Richard Dixon',
                popularity: 4.699,
                profile_path: '/rhMlmS9dE6pyy4qnZGRzlRrGlhh.jpg',
            },
            {
                character: 'Victor Timely / He Who Remains',
                credit_id: '6531de21b2681f00e13a7143',
                order: 581,
                adult: false,
                gender: 2,
                id: 1674162,
                known_for_department: 'Acting',
                name: 'Jonathan Majors',
                original_name: 'Jonathan Majors',
                popularity: 15.056,
                profile_path: '/nsxnMbkl9Lpc12AmYwKi9SmsJ7e.jpg',
            },
            {
                character: 'Guy Pennyman III',
                credit_id: '6531df409ac535087f3a9c93',
                order: 584,
                adult: false,
                gender: 0,
                id: 2061879,
                known_for_department: 'Acting',
                name: 'Ross Hatt',
                original_name: 'Ross Hatt',
                popularity: 0.6,
                profile_path: null,
            },
            {
                character: 'Councilman',
                credit_id: '6531df4a9ac53508763ca816',
                order: 585,
                adult: false,
                gender: 0,
                id: 1775216,
                known_for_department: 'Acting',
                name: 'Mark Fairclough',
                original_name: 'Mark Fairclough',
                popularity: 0.656,
                profile_path: null,
            },
            {
                character: 'Ticket Taker',
                credit_id: '6531df5bb2681f00c44e6c14',
                order: 586,
                adult: false,
                gender: 0,
                id: 3432441,
                known_for_department: 'Acting',
                name: "Ryan O'Doherty",
                original_name: "Ryan O'Doherty",
                popularity: 0.6,
                profile_path: null,
            },
            {
                character: 'Behemoth',
                credit_id: '6531df6648138200ff77d69e',
                order: 587,
                adult: false,
                gender: 0,
                id: 1539794,
                known_for_department: 'Acting',
                name: 'Alex Forman',
                original_name: 'Alex Forman',
                popularity: 0.6,
                profile_path: null,
            },
            {
                character: 'Newsie',
                credit_id: '6531df6f8d22fc00acb59dde',
                order: 588,
                adult: false,
                gender: 2,
                id: 2759641,
                known_for_department: 'Acting',
                name: 'Gus Turner',
                original_name: 'Gus Turner',
                popularity: 0.6,
                profile_path: '/6vrQGdQMdlyMwtlgeuC4zl3xUyp.jpg',
            },
            {
                character: 'Young Victor Timely',
                credit_id: '6531df7f48138200c5e3c631',
                order: 589,
                adult: false,
                gender: 0,
                id: 4319243,
                known_for_department: 'Acting',
                name: 'Nasri Thompson',
                original_name: 'Nasri Thompson',
                popularity: 0.6,
                profile_path: null,
            },
            {
                character: 'Heckler',
                credit_id: '6531df8a8d22fc00acb59dff',
                order: 590,
                adult: false,
                gender: 0,
                id: 4329574,
                known_for_department: 'Acting',
                name: 'Alasdair Baker',
                original_name: 'Alasdair Baker',
                popularity: 0.6,
                profile_path: null,
            },
            {
                character: 'On-Set Miss Minutes',
                credit_id: '6531df979ac535087b44defe',
                order: 591,
                adult: false,
                gender: 0,
                id: 3430591,
                known_for_department: 'Acting',
                name: 'Natasha Arancini',
                original_name: 'Natasha Arancini',
                popularity: 0.6,
                profile_path: '/spPXQtIvgRFAexkSQzovPXce3sc.jpg',
            },
        ],
    },
];
