export const cast = [
    {
        adult: false,
        gender: 2,
        id: 976,
        known_for_department: 'Acting',
        name: 'Jason Statham',
        original_name: 'Jason Statham',
        popularity: 179.242,
        profile_path: '/lldeQ91GwIVff43JBrpdbAAeYWj.jpg',
        cast_id: 7,
        character: 'Christmas',
        credit_id: '612d117104b596002a689d40',
        order: 0,
    },
    {
        adult: false,
        gender: 2,
        id: 62644,
        known_for_department: 'Acting',
        name: '50 Cent',
        original_name: '50 Cent',
        popularity: 13.663,
        profile_path: '/uyEfYdXj8lJusUyH7I7ChvhDXPH.jpg',
        cast_id: 10,
        character: 'Easy Day',
        credit_id: '612d118881140f002ab73f06',
        order: 1,
    },
    {
        adult: false,
        gender: 1,
        id: 19537,
        known_for_department: 'Acting',
        name: 'Megan Fox',
        original_name: 'Megan Fox',
        popularity: 56.798,
        profile_path: '/9khvk5svs81TLqIGlI3ZJqYtqaY.jpg',
        cast_id: 9,
        character: 'Gina',
        credit_id: '612d118004b5960043af5035',
        order: 2,
    },
    {
        adult: false,
        gender: 2,
        id: 16644,
        known_for_department: 'Acting',
        name: 'Dolph Lundgren',
        original_name: 'Dolph Lundgren',
        popularity: 59.147,
        profile_path: '/fisJpm05tw6GCJ4v62TKBCoWuZM.jpg',
        cast_id: 11,
        character: 'Gunner',
        credit_id: '612d11e52c6b7b006273001f',
        order: 3,
    },
    {
        adult: false,
        gender: 2,
        id: 57207,
        known_for_department: 'Acting',
        name: 'Tony Jaa',
        original_name: 'Tony Jaa',
        popularity: 29.925,
        profile_path: '/AdN11kgJeKgjyWPRTGSHjSPzG7N.jpg',
        cast_id: 8,
        character: 'Decha',
        credit_id: '612d1179001bbd0067885386',
        order: 4,
    },
    {
        adult: false,
        gender: 2,
        id: 113732,
        known_for_department: 'Acting',
        name: 'Iko Uwais',
        original_name: 'Iko Uwais',
        popularity: 31.35,
        profile_path: '/9WngJ2lOCy3UczLv3L2JRZvX0UM.jpg',
        cast_id: 38,
        character: 'Rahmat',
        credit_id: '61785057abf8e20060b106bc',
        order: 5,
    },
    {
        adult: false,
        gender: 2,
        id: 1271,
        known_for_department: 'Acting',
        name: 'Andy García',
        original_name: 'Andy García',
        popularity: 42.917,
        profile_path: '/8JehpGGaW6BU5m4e4QURlR8Isg8.jpg',
        cast_id: 30,
        character: 'Marsh',
        credit_id: '613bd8bf08cf87002a8db38f',
        order: 6,
    },
    {
        adult: false,
        gender: 2,
        id: 16483,
        known_for_department: 'Acting',
        name: 'Sylvester Stallone',
        original_name: 'Sylvester Stallone',
        popularity: 55.406,
        profile_path: '/pOpbPofjwpynRkWPZZZkyGds6rx.jpg',
        cast_id: 3,
        character: 'Barney',
        credit_id: '5de94330a313b80012940a54',
        order: 7,
    },
];
