export const movie = [
    {
        adult: false,
        backdrop_path: '/zYlgqIpqJ1VAbvFhRhktAzIybVs.jpg',
        id: 820609,
        title: 'No One Will Save You',
        original_language: 'en',
        original_title: 'No One Will Save You',
        overview: "An exiled anxiety-ridden homebody must battle an alien who's found its way into her home.",
        poster_path: '/ehGIDAMaYy6Eg0o8ga0oqflDjqW.jpg',
        media_type: 'movie',
        genre_ids: [27, 878, 53],
        popularity: 339.042,
        release_date: '2023-09-22',
        video: false,
        vote_average: 6.959,
        vote_count: 208,
        logo: 'https://www.themoviedb.org/t/p/original/1iRQXyityzQC5DXqzx9EODWu08F.png',
    },
    {
        adult: false,
        backdrop_path: '/xFYpUmB01nswPgbzi8EOCT1ZYFu.jpg',
        id: 980489,
        title: 'Gran Turismo',
        original_language: 'en',
        original_title: 'Gran Turismo',
        overview:
            'The ultimate wish-fulfillment tale of a teenage Gran Turismo player whose gaming skills won him a series of Nissan competitions to become an actual professional racecar driver.',
        poster_path: '/51tqzRtKMMZEYUpSYkrUE7v9ehm.jpg',
        media_type: 'movie',
        genre_ids: [28, 18, 12],
        popularity: 356.01,
        release_date: '2023-08-09',
        video: false,
        vote_average: 7.478,
        vote_count: 325,
        logo: 'https://www.themoviedb.org/t/p/original/fUId3nVEBYXXGC5knwQtyETEh0V.png',
    },
    {
        adult: false,
        backdrop_path: '/6fKEw0I2FTD5FLOQ5q7L1tqf876.jpg',
        id: 790493,
        title: 'Spy Kids: Armageddon',
        original_language: 'en',
        original_title: 'Spy Kids: Armageddon',
        overview:
            'When the children of the world’s greatest secret agents unwittingly help a powerful game developer unleash a computer virus that gives him control of all technology, they must become spies themselves to save their parents and the world.',
        poster_path: '/vd8YdaH7dzeIMGTNwQinlSiA1gV.jpg',
        media_type: 'movie',
        genre_ids: [10751, 35, 28, 12],
        popularity: 191.667,
        release_date: '2023-09-22',
        video: false,
        vote_average: 6.618,
        vote_count: 34,
        logo: 'https://www.themoviedb.org/t/p/original/p8q1ABV5cieMlP6nS85MZRW9qci.png',
    },
    {
        adult: false,
        backdrop_path: '/H6j5smdpRqP9a8UnhWp6zfl0SC.jpg',
        id: 565770,
        title: 'Blue Beetle',
        original_language: 'en',
        original_title: 'Blue Beetle',
        overview:
            'Recent college grad Jaime Reyes returns home full of aspirations for his future, only to find that home is not quite as he left it. As he searches to find his purpose in the world, fate intervenes when Jaime unexpectedly finds himself in possession of an ancient relic of alien biotechnology: the Scarab.',
        poster_path: '/mXLOHHc1Zeuwsl4xYKjKh2280oL.jpg',
        media_type: 'movie',
        genre_ids: [28, 878, 12],
        popularity: 4198.111,
        release_date: '2023-08-16',
        video: false,
        vote_average: 7.1,
        vote_count: 836,
    },
    {
        adult: false,
        backdrop_path: '/ctMserH8g2SeOAnCw5gFjdQF8mo.jpg',
        id: 346698,
        title: 'Barbie',
        original_language: 'en',
        original_title: 'Barbie',
        overview:
            'Barbie and Ken are having the time of their lives in the colorful and seemingly perfect world of Barbie Land. However, when they get a chance to go to the real world, they soon discover the joys and perils of living among humans.',
        poster_path: '/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg',
        media_type: 'movie',
        genre_ids: [35, 12, 14],
        popularity: 1598.743,
        release_date: '2023-07-19',
        video: false,
        vote_average: 7.287,
        vote_count: 4968,
        logo: 'https://www.themoviedb.org/t/p/original/nsMnkuWIZCBxkBLPi0ZXuRloYL2.png',
    },
    {
        adult: false,
        backdrop_path: '/rMvPXy8PUjj1o8o1pzgQbdNCsvj.jpg',
        id: 299054,
        title: 'Expend4bles',
        original_language: 'en',
        original_title: 'Expend4bles',
        overview:
            'Armed with every weapon they can get their hands on and the skills to use them, The Expendables are the world’s last line of defense and the team that gets called when all other options are off the table. But new team members with new styles and tactics are going to give “new blood” a whole new meaning.',
        poster_path: '/nbrqj9q8WubD3QkYm7n3GhjN7kE.jpg',
        media_type: 'movie',
        genre_ids: [28, 12, 53],
        popularity: 488.259,
        release_date: '2023-09-15',
        video: false,
        vote_average: 6.6,
        vote_count: 57,
        logo: 'https://www.themoviedb.org/t/p/original/7yehQ0O1KOtdWy7df8UpiqYwBX6.png',
    },
    {
        adult: false,
        backdrop_path: '/A8paSZwFPs5EmMGE2hbNGKqBfC5.jpg',
        id: 856289,
        title: 'Creation of the Gods I: Kingdom of Storms',
        original_language: 'zh',
        original_title: '封神第一部：朝歌风云',
        overview:
            'Based on the most well-known classical fantasy novel of China, Fengshenyanyi, the trilogy is a magnificent eastern high fantasy epic that recreates the prolonged mythical wars between humans, immortals and monsters, which happened more than three thousand years ago.',
        poster_path: '/ccJpK0rqzhQeP7Mrs2uKqObFY4L.jpg',
        media_type: 'movie',
        genre_ids: [28, 14, 10752],
        popularity: 312.972,
        release_date: '2023-07-20',
        video: false,
        vote_average: 7.5,
        vote_count: 82,
        logo: 'https://www.themoviedb.org/t/p/original/k1RzjRkrZAUAfZ8DC8fqjYJgJ33.png',
    },
    {
        adult: false,
        backdrop_path: '/1yhQqbi1rZg9EJiOI22i8Xg7vW.jpg',
        id: 814776,
        title: 'Bottoms',
        original_language: 'en',
        original_title: 'Bottoms',
        overview:
            'Unpopular best friends PJ and Josie start a high school self-defense club to meet girls and lose their virginity. They soon find themselves in over their heads when the most popular students start beating each other up in the name of self-defense.',
        poster_path: '/jeyTQrNEpyE1LZIgVlswYh3sc34.jpg',
        media_type: 'movie',
        genre_ids: [35],
        popularity: 120.061,
        release_date: '2023-08-25',
        video: false,
        vote_average: 7.189,
        vote_count: 45,
        logo: 'https://www.themoviedb.org/t/p/original/4bbBrp0x5dNdJHAbc1N6xdHZm0L.png',
    },
    {
        adult: false,
        backdrop_path: '/v409ZmpZqHI8ZhrgQTzr6tu97jr.jpg',
        id: 866346,
        title: 'The Retirement Plan',
        original_language: 'en',
        original_title: 'The Retirement Plan',
        overview:
            'When Ashley and her young daughter Sarah get caught up in a criminal enterprise that puts their lives at risk, she turns to the only person who can help: her estranged father Matt, currently living the life of a retired beach bum in the Cayman Islands. Their reunion is fleeting as they are soon tracked down on the island by crime boss Donnie and his lieutenant Bobo. As Ashley, Sarah, and Matt become entangled in an increasingly dangerous web, Ashley quickly learns her father had a secret past that she knew nothing about and that there is more to her father than meets the eye.',
        poster_path: '/kv4n3xgRWtkldaD4kyy1FvpW6bO.jpg',
        media_type: 'movie',
        genre_ids: [35, 28],
        popularity: 73.244,
        release_date: '2023-08-24',
        video: false,
        vote_average: 7,
        vote_count: 10,
    },
    {
        adult: false,
        backdrop_path: '/9WxqnP9c29wXd03sALSpxpTx8fk.jpg',
        id: 1172009,
        title: 'The Black Book',
        original_language: 'en',
        original_title: 'The Black Book',
        overview:
            'After his son is wrongly accused of kidnapping, a deacon who has just lost his wife takes matters into his own hands and fights a crooked police gang to clear him.',
        poster_path: '/wUvUcLTxc83k4l8psyO2pDYHHB3.jpg',
        media_type: 'movie',
        genre_ids: [9648, 53, 28],
        popularity: 107.614,
        release_date: '2023-09-22',
        video: false,
        vote_average: 7.7,
        vote_count: 9,
    },
    {
        adult: false,
        backdrop_path: '/iIvQnZyzgx9TkbrOgcXx0p7aLiq.jpg',
        id: 1008042,
        title: 'Talk to Me',
        original_language: 'en',
        original_title: 'Talk to Me',
        overview:
            'When a group of friends discover how to conjure spirits using an embalmed hand, they become hooked on the new thrill, until one of them goes too far and unleashes terrifying supernatural forces.',
        poster_path: '/kdPMUMJzyYAc4roD52qavX0nLIC.jpg',
        media_type: 'movie',
        genre_ids: [27, 53],
        popularity: 1762.732,
        release_date: '2023-07-26',
        video: false,
        vote_average: 7.234,
        vote_count: 836,
    },
    {
        adult: false,
        backdrop_path: '/iQcCAm8hKWZyUntqrvzyEGtXyJl.jpg',
        id: 670292,
        title: 'The Creator',
        original_language: 'en',
        original_title: 'The Creator',
        overview:
            'Amid a future war between the human race and the forces of artificial intelligence, a hardened ex-special forces agent grieving the disappearance of his wife, is recruited to hunt down and kill the Creator, the elusive architect of advanced AI who has developed a mysterious weapon with the power to end the war—and mankind itself.',
        poster_path: '/vBZ0qvaRxqEhZwl6LWmruJqWE8Z.jpg',
        media_type: 'movie',
        genre_ids: [878, 28, 53],
        popularity: 211.878,
        release_date: '2023-09-27',
        video: false,
        vote_average: 7.7,
        vote_count: 5,
    },
    {
        adult: false,
        backdrop_path: '/2vLhatnKrAXGOesLth1lhz76JTg.jpg',
        id: 950071,
        title: 'Jaane Jaan',
        original_language: 'hi',
        original_title: 'जाने जां',
        overview:
            'When a single mother her teenage daughter becomes ensnared in a deadly crime,  find an unexpected ally in their neighbor, a simple, doting but genius teacher math teacher comes to aid, while a tenacious cop digs into the case.',
        poster_path: '/oaUOV9VCNM5MjrmonqgH4o3XNwQ.jpg',
        media_type: 'movie',
        genre_ids: [80, 53],
        popularity: 176.434,
        release_date: '2023-09-21',
        video: false,
        vote_average: 7.063,
        vote_count: 24,
    },
    {
        adult: false,
        backdrop_path: '/4fLZUr1e65hKPPVw0R3PmKFKxj1.jpg',
        id: 976573,
        title: 'Elemental',
        original_language: 'en',
        original_title: 'Elemental',
        overview:
            'In a city where fire, water, land and air residents live together, a fiery young woman and a go-with-the-flow guy will discover something elemental: how much they have in common.',
        poster_path: '/4Y1WNkd88JXmGfhtWR7dmDAo1T2.jpg',
        media_type: 'movie',
        genre_ids: [16, 35, 10751, 14, 10749],
        popularity: 1009.664,
        release_date: '2023-06-14',
        video: false,
        vote_average: 7.764,
        vote_count: 2353,
    },
    {
        adult: false,
        backdrop_path: '/53z2fXEKfnNg2uSOPss2unPBGX1.jpg',
        id: 968051,
        title: 'The Nun II',
        original_language: 'en',
        original_title: 'The Nun II',
        overview:
            'In 1956 France, a priest is violently murdered, and Sister Irene begins to investigate. She once again comes face-to-face with a powerful evil.',
        poster_path: '/5gzzkR7y3hnY8AD1wXjCnVlHba5.jpg',
        media_type: 'movie',
        genre_ids: [27, 9648, 53],
        popularity: 1428.836,
        release_date: '2023-09-06',
        video: false,
        vote_average: 6.6,
        vote_count: 303,
    },
    {
        adult: false,
        backdrop_path: '/dcqfqpAFBDP5K7rhNgUY6YVEVh3.jpg',
        id: 1168521,
        title: 'Dark Asset',
        original_language: 'en',
        original_title: 'Dark Asset',
        overview:
            'A charming guy attempts to pick up a woman in a bar by spinning a tale involving spies, implanted microchips and the dangerous military scientist hunting him.',
        poster_path: '/hfxqsC8Bz2wMZmXKwEZqKyJiScT.jpg',
        media_type: 'movie',
        genre_ids: [28, 53, 878],
        popularity: 27.054,
        release_date: '2023-09-22',
        video: false,
        vote_average: 7.5,
        vote_count: 2,
    },
    {
        adult: false,
        backdrop_path: '/8UjwvrxTpsD46cDQklDdU14RQYB.jpg',
        id: 1146348,
        title: 'Scooby-Doo! And Krypto, Too!',
        original_language: 'en',
        original_title: 'Scooby-Doo! And Krypto, Too!',
        overview:
            "When the Justice League goes missing and villains overrun Metropolis, there's only one team that can solve this mystery: Scooby-Doo and the gang! But wait, there's a new dog in town – Krypto – Superman's Superdog with Super Powers. Mystery Inc. will need all the help it can get when phantoms menace the Justice League's headquarters.",
        poster_path: '/uVBtqBJbdh04VMjfjWw4J3DjXg.jpg',
        media_type: 'movie',
        genre_ids: [16, 10751, 9648, 14],
        popularity: 54.597,
        release_date: '2023-09-26',
        video: false,
        vote_average: 7,
        vote_count: 1,
    },
    {
        adult: false,
        backdrop_path: '/w2nFc2Rsm93PDkvjY4LTn17ePO0.jpg',
        id: 614930,
        title: 'Teenage Mutant Ninja Turtles: Mutant Mayhem',
        original_language: 'en',
        original_title: 'Teenage Mutant Ninja Turtles: Mutant Mayhem',
        overview:
            "After years of being sheltered from the human world, the Turtle brothers set out to win the hearts of New Yorkers and be accepted as normal teenagers through heroic acts. Their new friend April O'Neil helps them take on a mysterious crime syndicate, but they soon get in over their heads when an army of mutants is unleashed upon them.",
        poster_path: '/ueO9MYIOHO7M1PiMUeX74uf8fB9.jpg',
        media_type: 'movie',
        genre_ids: [16, 35, 28],
        popularity: 580.352,
        release_date: '2023-07-31',
        video: false,
        vote_average: 7.343,
        vote_count: 607,
    },
    {
        adult: false,
        backdrop_path: '/kHlX3oqdD4VGaLpB8O78M25KfdS.jpg',
        id: 945729,
        title: 'A Haunting in Venice',
        original_language: 'en',
        original_title: 'A Haunting in Venice',
        overview:
            'Celebrated sleuth Hercule Poirot, now retired and living in self-imposed exile in Venice, reluctantly attends a Halloween séance at a decaying, haunted palazzo. When one of the guests is murdered, the detective is thrust into a sinister world of shadows and secrets.',
        poster_path: '/1Xgjl22MkAZQUavvOeBqRehrvqO.jpg',
        media_type: 'movie',
        genre_ids: [9648, 53, 80],
        popularity: 226.114,
        release_date: '2023-09-13',
        video: false,
        vote_average: 6.778,
        vote_count: 435,
    },
    {
        adult: false,
        backdrop_path: '/rhuqWhQ2gmy8toUiDtpuHCdUt5j.jpg',
        id: 1040892,
        title: 'Slotherhouse',
        original_language: 'en',
        original_title: 'Slotherhouse',
        overview:
            'Wanting to have a killer year, sorority sister Emily Young realizes she might just be the best option for her sorority. While beginning her campaign, she finds an adorable sloth that steals her heart and soon realizes she just might steal the hearts, and votes, of her sorority sisters. But when bodies slowly begin to pile up in the Sigma Lambda Theta house, Emily and her sorority sisters realize the deaths are being caused by their new house mascot, the cuddly sloth Alpha. Will Emily and her sisters escape the house with their lives? Or is this death-sloth with three razor sharp claws too quick for them?',
        poster_path: '/pLSoVBuBa3aqFBgBY2puu3BN8of.jpg',
        media_type: 'movie',
        genre_ids: [35, 27, 53],
        popularity: 22.182,
        release_date: '2023-08-30',
        video: false,
        vote_average: 4.857,
        vote_count: 7,
    },
];
